#!/bin/bash
#PBS -P e14
#PBS -q normal
#PBS -l walltime=10:00:00
#PBS -l mem=50GB
#PBS -l ncpus=1
#PBS -l wd
#PBS -M astellemas@gmail.com
#PBS -m abe

module use /g/data3/hh5/public/modules
module load conda/analysis3-19.07

python /g/data/e14/as3189/OFAM/scripts/base_ten.py
