#!/bin/bash
#PBS -P e14
#PBS -q normal
#PBS -l walltime=29:00:00
#PBS -l mem=60GB
#PBS -l ncpus=1
#PBS -l wd
#PBS -M astellemas@gmail.com
#PBS -m abe

module use /g/data3/hh5/public/modules
module load conda/analysis3-19.07

python /g/data/e14/as3189/OFAM/scripts/velocity_profile.py
